### PR TITLE
ListBox now works with HasEnabled interface.

### LINKED ISSUE #10: Apply HasEnabled interface
Make sure there is a demo for showing the component as disabled.

### PR DESCRIPTION
**Pull request by caalador**
Updated ListBox to work with HasEnabled and
added a disabled test.

Closes #10

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 62 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nIP8O-yVQw8LFzS6A:-L9nIP8O-yVQw8LFzS6B:bgd2s0d) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/086f53d36c4a6f4d5c7cf3e59c1273fd0cf51426/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L62)):*
> ```
> public void setEnabled(boolean enabled) {
> ```

`HasComponents extends HasEnabled` .
So this method is overridden, right ?
Should be annotation at least. But a question: should it be overridden at all ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 64 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nNZw44ywwN0KGwWmW:-L9nNZw44ywwN0KGwWmX:bauhpbg) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L64)):*
> ```Java
>      */
>     @Override
>     public void setEnabled(boolean enabled) {
> ```

Set enabled is overridden due to the fact that the VaadinItem is a TextProvider which doesn't support isEnabled.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 64 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nNZw44ywwN0KGwWmW:-L9nQ2EG4swSPmTBSBGW:b6b4ur3) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Set enabled is overridden due to the fact that the VaadinItem is a TextProvider which doesn't support isEnabled.
</blockquote></details>

Item is a text element....
Then how does `getElement().setProperty()` work at all?
It should throw an exception since it's `AbstractTextElementStateProvider` .

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 74 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nPtS8EBbpAMKCNzR4:-L9nPtS8EBbpAMKCNzR5:by9ux7v) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L74)):*
> ```
> public boolean isDisabled() {
> ```

I think it still should be `isEnabled`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 64 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nNZw44ywwN0KGwWmW:-L9nT_U0ERNEBotBkEVu:b-d92rkb) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L64)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Item is a text element....
Then how does `getElement().setProperty()` work at all?
It should throw an exception since it's `AbstractTextElementStateProvider` .
</blockquote></details>

That is a good question. Where do the Providers get determined?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 64 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nNZw44ywwN0KGwWmW:-L9na_9Q8d3LJwhAogWL:bxuuyg5) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L64)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

That is a good question. Where do the Providers get determined?
</blockquote></details>

At the element creation phase.
See `Element.get()` methods.
Or `Element` CTOR  which accepts tag ( used with a component CTOR). But it always uses `BasicElementStateProvider`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 64 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nNZw44ywwN0KGwWmW:-L9nd9OW8uYP045MyC3c:b-ycwsuc) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L64)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

At the element creation phase.
See `Element.get()` methods.
Or `Element` CTOR  which accepts tag ( used with a component CTOR). But it always uses `BasicElementStateProvider`.
</blockquote></details>

The problem is actually not the VaadinItem, but the encapsulated item that was a TextNode. so this is not needed.

---

*[src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java, line 74 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9nPtS8EBbpAMKCNzR4:-L9ndUL38ZmfTgABZh4u:brpmqc3) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/bd0855c52c423d8ef389d80049b577cba1c29019/src/main/java/com/vaadin/flow/component/listbox/VaadinItem.java#L74)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> public boolean isDisabled() {
> ```

I think it still should be `isEnabled`.
</blockquote></details>

removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-:-L9ngPjt54CrNGuFYaxu:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java, line 53 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9o4Fua8_bTFE5TLupN:-L9o4Fub6g1gXqVEsNLZ:b-bb2tt1) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/f4c8d8ec85c5fce650b11477c3771f261f861f30/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java#L53)):*
> ```
>             Assert.assertNotNull(listBox.getElement().getChild(index)
>                     .getAttribute("disabled"));
> ```

Curly brackets please here and below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by caalador** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java, line 53 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-L9o4Fua8_bTFE5TLupN:-L9o4njy2age6KknVfnQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-box-flow/blob/f4c8d8ec85c5fce650b11477c3771f261f861f30/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxUnitTest.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>             Assert.assertNotNull(listBox.getElement().getChild(index)
>                     .getAttribute("disabled"));
> ```

Curly brackets please here and below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-box-flow/19#-:-L9o5gu5EdqOW21avlB6:bnfp4nl)*

**Pull request merged**
